### PR TITLE
feat: added login page styling

### PR DESCRIPTION
**Pull request by pranjaltimsina**
# Pull Request Type
Please check the type of change your PR introduces:
- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

# Purpose
- Added styles to the login page

# Does this PR introduce any new bug?
- [ ] Yes
- [ ] No
- [X] Maybe

#### Issue Reference: #4 

# Other information

# Did you learn something new?
- CSS

### CODE REVIEW

**Comment by Nirmitjatana** [comment]
@BRO3886 can we add Netlify preview for this repo?

**Comment by BRO3886** [comment]
> @BRO3886 can we add Netlify preview for this repo?

I'll add cloudfare wait

**Comment by Nirmitjatana** [comment]
@BRO3886 any update on the Cloudflare preview?

**Comment by BRO3886** [comment]
> @BRO3886 any update on the Cloudflare preview?

Ig it'll start working after I merge this PR, tried contacting cloudfare but no response, previews start coming in after the main branch is deployed

**Comment by BRO3886** [comment]
Merging.

**Pull request merged**
